[package]
name = "general"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3.23.0"
serde_json = "1.0"
arc-swap = "1.7.1"
tracing = "0.1.41"
bincode = "2.0.1"
memmap2 = "0.9.9"
parking_lot = "0.12.5"